max-pages: 14
default-pages: 1
autosave-minutes: 5

database:
  type: sqlite   # sqlite / mysql
  sqlite:
    file: enderchest.db
  mysql:
    host: localhost
    port: 3306
    database: venderchest
    username: root
    password: ""
    pool-size: 5

# Ítems que no pueden guardarse en el enderchest
blacklist: []
